const columns = [
  { name: "ID", uid: "productID" },
  { name: "NAME", uid: "name" },
  { name: "QUANTITY", uid: "quantity" },
  { name: "TOTAL", uid: "totalPrice" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];

const purchases = [
  {
    producID: 2150001,
    name: "Taylor Swift",
    description: "CD",
    pricePerProduct: 10.99,
    quantity: 3,
    status: "processing", 
  },
  {
    producID: 2150002,
    name: "Fearless",
    description: "CD",
    pricePerProduct: 11.99,
    quantity: 2,
    status: "shipping"
  },
  {
    producID: 2150003,
    name: "Speak Now",
    description: "CD",
    pricePerProduct: 13.99,
    quantity: 1,
    status: "completed",
  },
  {
    producID: 2150004,
    name: "Red",
    description: "CD",
    pricePerProduct: 13.99,
    quantity: 4,
    status: "cancelled",
  },
  {
    producID: 2150005,
    name: "1989",
    description: "CD",
    pricePerProduct: 11.99,
    quantity: 3,
    status: "delayed",
  },
  {
    producID: 2150006,
    name: "reputation",
    description: "CD",
    pricePerProduct: 11.99,
    quantity: 1,
    status: "processing",
  },
  {
    producID: 2150007,
    name: "Lover",
    description: "CD",
    pricePerProduct: 13.99,
    quantity: 5,
    status: "shipping",
  },
  {
    producID: 2150008,
    name: "folklore",
    description: "Vinyl",
    pricePerProduct: 39.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150009,
    name: "evermore",
    description: "Vinyl",
    pricePerProduct: 37.99,
    quantity: 2,
    status: "cancelled",
  },
  {
    producID: 2150010,
    name: "Fearless (Taylor's Version)",
    description: "CD",
    pricePerProduct: 13.99,
    quantity: 5,
    status: "delayed",
  },
  {
    producID: 2150011,
    name: "Red (Taylor's Version)",
    description: "Vinyl",
    pricePerProduct: 35.99,
    quantity: 2,
    status: "processing",
  },
  {
    producID: 2150012,
    name: "Midnights",
    description: "Vinyl",
    pricePerProduct: 33.99,
    quantity: 3,
    status: "shipping",
  },
  {
    producID: 2150013,
    name: "Speak Now (Taylor's Version)",
    description: "Vinyl",
    pricePerProduct: 34.99,
    quantity: 1,
    status: "completed",
  },
  {
    producID: 2150014,
    name: "1989 (Taylor's Version)",
    description: "Vinyl",
    pricePerProduct: 34.99,
    quantity: 4,
    status: "completed",
  },
  {
    producID: 2150015,
    name: "THE TORTURED POETS DEPARTMENT",
    description: "Vinyl",
    pricePerProduct: 34.99,
    quantity: 1,
    status: "completed",
  },
  {
    producID: 2150016,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "CD",
    pricePerProduct: 14.99,
    quantity: 3,
    status: "completed",
  },
];

export { columns, purchases };