const columns = [
  { name: "ID", uid: "productID" },
  { name: "NAME", uid: "name" },
  { name: "QUANTITY", uid: "quantity" },
  { name: "TOTAL", uid: "totalPrice" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];

const purchases = [
  {
    producID: 2150001,
    name: "Speak Now (Taylor's Version)",
    description: "CD",
    pricePerProduct: 10.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
];

export { columns, purchases };