const columns = [
  { name: "ID", uid: "productID" },
  { name: "NAME", uid: "name" },
  { name: "QUANTITY", uid: "quantity" },
  { name: "TOTAL", uid: "totalPrice" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];

const purchases = [
  {
    producID: 2150001,
    name: "Speak Now (Taylor's Version)",
    description: "CD",
    pricePerProduct: 10.99,
    quantity: 3,
    status: "processing",
  },
  {
    producID: 2150002,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "shipping",
  },
  {
    producID: 2150003,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150004,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "cancelled",
  },
  {
    producID: 2150005,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "delayed",
  },
  {
    producID: 2150006,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "processing",
  },
  {
    producID: 2150007,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "shipping",
  },
  {
    producID: 2150008,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
  {
    producID: 2150009,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "cancelled",
  },
  {
    producID: 2150010,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "delayed",
  },
  {
    producID: 2150011,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "processing",
  },
  {
    producID: 2150012,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "shipping",
  },
  {
    producID: 2150013,
    name: "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY",
    description: "Vinyl",
    pricePerProduct: 49.99,
    quantity: 3,
    status: "completed",
  },
];

export { columns, purchases };